import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Header } from "./header";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-[#E6F2F2] dark:bg-[#001415] front-sans antialiased")}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
